import { Language } from './types.ts';

export const STRINGS = {
  [Language.EN]: {
    // General
    appName: "Marketing AI",
    loading: "Generating...",
    generate: "Generate",
    error: "An error occurred. Please try again.",
    noResults: "No results generated yet. Enter details above and click the generate button.",
    copy: "Copy",
    copied: "Copied!",
    share: "Share",
    callToAction: "Call to Action",
    comingSoon: "Coming Soon",
    featureInDevelopment: "This feature is currently in development. Stay tuned for powerful analytics and insights!",
    sources: "Sources",

    // Subscription
    subscriptionRequired: "Subscription Required",
    subscriptionMessage: "You need an active subscription to access this feature. Please subscribe to unlock all tools.",
    subscribeNow: "Subscribe Now",

    // Sidebar & Bottom Nav
    dashboard: "Dashboard",
    adsAi: "Ads AI",
    shortForm: "Short-form Factory",
    smm: "SMM",
    influencers: "Influencers",
    landingPages: "Landing Pages",
    emailMarketing: "Email Marketing",
    affiliateMarketing: "Affiliate Marketing",
    crm: "CRM",
    analytics: "Analytics",
    more: "More",

    // Header
    toggleTheme: "Toggle Theme",
    changeLanguage: "Change Language",
    welcome: "Welcome to Marketing AI",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",

    // Login
    login: "Login",
    emailLabel: "Email",
    passwordLabel: "Password",
    emailPlaceholder: "email@example.com",
    passwordPlaceholder: "********",
    loginError: "Failed to login. Please check your credentials.",
    noAccount: "Don't have an account?",
    signUp: "Sign up",

    // SignUp
    createAccount: "Create Account",
    nameLabel: "Name",
    namePlaceholder: "Your full name",
    confirmPasswordLabel: "Confirm Password",
    passwordMismatchError: "Passwords do not match.",
    alreadyHaveAccount: "Already have an account?",
    signupSuccessTitle: "Check your email",
    signupSuccessMessage: "We've sent a verification link to your email address. Please click the link to activate your account.",
    backToLogin: "Back to Login",

    // Config Warning
    configNeeded: "Configuration Needed!",
    updateSupabaseCredentials: "Please update your Supabase credentials in `services/supabaseClient.ts` to enable authentication.",

    // More View
    moreTitle: "All Tools",

    // Dashboard
    dashboardTitle: "Dashboard",
    dashboardDescription: "Your central hub for AI-powered marketing tools. Select a tool to begin.",
    adsCardDescription: "Generate ad copy, manage campaigns, and get smart targeting suggestions.",
    contentCardDescription: "Produce short-form content with templates and performance analytics.",
    smmCardDescription: "Manage social accounts, schedule posts, and automate engagement.",
    influencersCardDescription: "Find relevant influencers in your niche and location to boost your campaigns.",
    landingPagesCardDescription: "Create high-converting landing pages with A/B testing capabilities.",
    emailCardDescription: "Build and automate email campaigns with list segmentation.",
    affiliateCardDescription: "Manage your affiliate network, track sales, and create custom links.",
    crmCardDescription: "Track the customer journey and automate follow-ups with an integrated CRM.",
    analyticsCardDescription: "Access a unified dashboard with all your key marketing metrics and insights.",

    // Ads Assistant
    adsTitle: "AI Ads Assistant",
    adsDescription: "Describe your product and audience to generate creative ad ideas.",
    productName: "Product/Service Name",
    productNamePlaceholder: "e.g., 'Handmade leather sandals'",
    targetAudience: "Target Audience",
    targetAudiencePlaceholder: "e.g., 'Fashion-conscious men aged 25-40 in Dubai'",
    sellingPoints: "Key Selling Points (one per line)",
    sellingPointsPlaceholder: "e.g.,\nGenuine Italian leather\nComfortable and durable\nFree shipping in GCC",
    generateAdIdeas: "Generate Ad Ideas",
    adIdeas: "Ad Ideas",
    adAngle: "Ad Angle",
    headline: "Headline",
    bodyCopy: "Body Copy",

    // Content Assistant
    contentTitle: "Short-form Content Factory",
    contentDescription: "Generate ready-to-publish short clip ideas from text or an image.",
    longContent: "Article/Transcript",
    longContentPlaceholder: "Paste your full article or video transcript here...",
    generateShortClips: "Generate Short Clips",
    shortClipIdeas: "Short Clip Ideas",
    clipTitle: "Clip Title",
    clipHook: "Hook",
    clipScript: "Script",
    visualSuggestion: "Visual Suggestion",
    fromText: "From Text",
    fromImage: "From Image",
    uploadImage: "Upload Image",
    imagePrompt: "Prompt",
    imagePromptPlaceholder: "e.g., 'Create a 15-second TikTok script about this product'",

    // SMM
    smmTitle: "Social Media Content Plan",
    smmDescription: "Generate a content plan for a week, enhanced with relevant trends and events.",
    campaignTopic: "Campaign Topic / Theme",
    campaignTopicPlaceholder: "e.g., 'Ramadan special offers'",
    platform: "Platform",
    numberOfPosts: "Number of Posts",
    generatePlan: "Generate Plan",
    smmResults: "Generated Content Plan",
    day: "Day",
    contentType: "Content Type",
    caption: "Caption",
    hashtags: "Hashtags",
    
    // Landing Pages
    landingPagesTitle: "AI Landing Page Copywriter",
    landingPagesDescription: "Describe your product to generate compelling copy for a high-converting landing page.",
    productDescription: "Product/Service Description",
    productDescriptionPlaceholder: "e.g., An online course teaching Arabic calligraphy for beginners.",
    generateCopy: "Generate Copy",
    landingPageCopy: "Landing Page Copy",
    subheadline: "Subheadline",

    // Email Marketing
    emailMarketingTitle: "AI Email Campaign Generator",
    emailMarketingDescription: "Define your campaign goal to generate a sequence of effective marketing emails.",
    campaignGoal: "Campaign Goal",
    campaignGoalPlaceholder: "e.g., A 3-day flash sale for our new collection.",
    generateEmails: "Generate Emails",
    emailCampaignIdeas: "Email Campaign Ideas",
    subject: "Subject",
    
    // Affiliate Marketing
    affiliateMarketingTitle: "Affiliate Outreach AI",
    affiliateMarketingDescription: "Generate a professional email to recruit new affiliates for your program.",
    affiliateOffer: "Affiliate Offer",
    affiliateOfferPlaceholder: "e.g., 20% commission on all sales, 30-day cookie life.",
    generateOutreach: "Generate Outreach Email",
    outreachEmail: "Outreach Email",
    
    // CRM
    crmTitle: "AI Customer Persona Builder",
    crmDescription: "Describe your target audience to create a detailed customer persona for strategic planning.",
    audienceDescriptionPlaceholder: "e.g., Young professionals in the GCC who are tech-savvy and interested in sustainable products.",
    generatePersona: "Generate Persona",
    customerPersona: "Customer Persona",
    demographics: "Demographics",
    goals: "Goals",
    painPoints: "Pain Points",
    
    // Analytics
    adAnalyticsTitle: "Ad Analytics",
    keyMetrics: "Key Metrics",
    totalReach: "Total Reach",
    engagementRate: "Engagement Rate",
    conversions: "Conversions",
    adSpend: "Ad Spend",
    performanceOverTime: "Performance Over Time",
    channelPerformance: "Channel Performance",
    topPerformingCampaigns: "Top Performing Campaigns",
    campaign: "Campaign",
    status: "Status",
    spend: "Spend",
    results: "Results",
    connectAccountsPrompt: "Connect your ad accounts to see your performance data.",
    connectAccountsDescription: "Go to settings to connect your Facebook and Instagram accounts and unlock your ad analytics dashboard.",
    goToSettings: "Go to Settings",

    // SEO
    seoTitle: "AI SEO Assistant",
    seoDescription: "Get keyword suggestions and generate content briefs to rank higher on search engines.",
    searchDisclaimer: "Results are generated with the help of Google Search and may not be fully comprehensive or up-to-date.",
    topicPlaceholder: "e.g., 'Best coffee shops in Riyadh'",
    generateKeywords: "Generate Keywords",
    generateBrief: "Generate Content Brief",
    keywords: "Keywords",
    searchIntent: "Search Intent",
    contentBrief: "Content Brief",
    title: "Title",
    hook: "Hook",
    introduction: "Introduction",
    bodySections: "Body Sections",
    metaDescription: "SEO Meta Description",

    // Influencer
    influencersTitle: "AI Influencer Discovery",
    influencersDescription: "Find relevant influencers in your niche and location.",
    influencerDisclaimer: "This tool provides suggestions based on public data and Google Search. Always verify influencer credentials.",
    city: "City",
    cityPlaceholder: "e.g., 'Jeddah'",
    category: "Category / Niche",
    categoryPlaceholder: "e.g., 'Food Blogger'",
    followerRange: "Follower Range",
    findInfluencers: "Find Influencers",
    influencerResults: "Influencer Suggestions",
    followers: "Followers",
    bio: "Bio",
    viewProfile: "View Profile",

    // Optimizer
    optimizerTitle: "Social Media Optimizer",
    optimizerDescription: "Get recommendations on the best times to post and content ideas based on your industry.",
    industry: "Industry / Niche",
    industryPlaceholder: "e.g., 'E-commerce Fashion'",
    getRecommendations: "Get Recommendations",
    optimizerResults: "Optimization Suggestions",
    postingTimes: "Best Posting Times",
    contentIdeas: "Content Ideas",

    // Testing Suite
    testingTitle: "API Test Suite",
    testingDescription: "Run a series of automated tests against the Gemini API to ensure all endpoints are functioning correctly.",
    runTests: "Run All Tests",
    running: "Running...",
    testResults: "Test Results",
    passed: "Passed",
    failed: "Failed",

    // Settings
    settingsTitle: "Settings",
    connections: "Connections",
    connectionsDescription: "Connect your social media and ad accounts to unlock powerful analytics and automation features.",
    connect: "Connect",
    disconnect: "Disconnect",
    connected: "Connected",
    
    // OAuth Flow
    connectToPlatform: "Connect to {platform}",
    permissionsRequest: "This will allow Marketing AI to:",
    readAdPerformance: "Read ad performance data",
    allow: "Allow",
    cancel: "Cancel",
    finalizingConnection: "Finalizing Connection...",
    connectionSuccessful: "Connection Successful!",
    redirectingMessage: "Redirecting you back to settings...",
    connectionFailed: "Connection Failed",
    connectionErrorMessage: "Something went wrong. Please try again.",
    backToSettings: "Back to Settings",
    redirectingToPlatform: "Redirecting you to {platform}...",

  },
  [Language.AR]: {
    // General
    appName: "مسوّق الذكاء الاصطناعي",
    loading: "جاري الإنشاء...",
    generate: "إنشاء",
    error: "حدث خطأ. يرجى المحاولة مرة أخرى.",
    noResults: "لم يتم إنشاء أي نتائج بعد. أدخل التفاصيل أعلاه وانقر على زر الإنشاء.",
    copy: "نسخ",
    copied: "تم النسخ!",
    share: "مشاركة",
    callToAction: "دعوة لاتخاذ إجراء",
    comingSoon: "قريباً",
    featureInDevelopment: "هذه الميزة قيد التطوير حاليًا. ترقبوا تحليلات ورؤى قوية!",
    sources: "المصادر",

    // Subscription
    subscriptionRequired: "الاشتراك مطلوب",
    subscriptionMessage: "تحتاج إلى اشتراك نشط للوصول إلى هذه الميزة. يرجى الاشتراك لفتح جميع الأدوات.",
    subscribeNow: "اشترك الآن",

    // Sidebar & Bottom Nav
    dashboard: "لوحة التحكم",
    adsAi: "إعلانات AI",
    shortForm: "مصنع المحتوى القصير",
    smm: "إدارة التواصل الاجتماعي",
    influencers: "المؤثرون",
    landingPages: "صفحات الهبوط",
    emailMarketing: "التسويق عبر البريد",
    affiliateMarketing: "التسويق بالعمولة",
    crm: "إدارة علاقات العملاء",
    analytics: "التحليلات",
    more: "المزيد",

    // Header
    toggleTheme: "تغيير المظهر",
    changeLanguage: "تغيير اللغة",
    welcome: "أهلاً بك في مسوّق الذكاء الاصطناعي",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",

    // Login
    login: "تسجيل الدخول",
    emailLabel: "البريد الإلكتروني",
    passwordLabel: "كلمة المرور",
    emailPlaceholder: "email@example.com",
    passwordPlaceholder: "********",
    loginError: "فشل تسجيل الدخول. يرجى التحقق من بياناتك.",
    noAccount: "ليس لديك حساب؟",
    signUp: "أنشئ حساباً",

    // SignUp
    createAccount: "إنشاء حساب",
    nameLabel: "الاسم",
    namePlaceholder: "اسمك الكامل",
    confirmPasswordLabel: "تأكيد كلمة المرور",
    passwordMismatchError: "كلمتا المرور غير متطابقتين.",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    signupSuccessTitle: "تحقق من بريدك الإلكتروني",
    signupSuccessMessage: "لقد أرسلنا رابط تحقق إلى عنوان بريدك الإلكتروني. يرجى النقر على الرابط لتفعيل حسابك.",
    backToLogin: "العودة لتسجيل الدخول",

    // Config Warning
    configNeeded: "الإعداد مطلوب!",
    updateSupabaseCredentials: "يرجى تحديث بيانات اعتماد Supabase في `services/supabaseClient.ts` لتمكين المصادقة.",

    // More View
    moreTitle: "جميع الأدوات",

    // Dashboard
    dashboardTitle: "لوحة التحكم",
    dashboardDescription: "مركزك الرئيسي لأدوات التسويق المدعومة بالذكاء الاصطناعي. اختر أداة للبدء.",
    adsCardDescription: "أنشئ نصوصًا إعلانية، وأدر حملاتك، واحصل على اقتراحات استهداف ذكية.",
    contentCardDescription: "أنتج محتوى قصيرًا باستخدام القوالب وتحليلات الأداء.",
    smmCardDescription: "أدر حسابات التواصل الاجتماعي، وجدول المنشورات، وأتمتة التفاعل.",
    influencersCardDescription: "ابحث عن المؤثرين المناسبين في مجالك وموقعك لتعزيز حملاتك.",
    landingPagesCardDescription: "أنشئ صفحات هبوط عالية التحويل مع إمكانيات اختبار A/B.",
    emailCardDescription: "أنشئ حملات بريد إلكتروني وأتمتتها مع تقسيم القوائم.",
    affiliateCardDescription: "أدر شبكة التسويق بالعمولة، وتتبع المبيعات، وأنشئ روابط مخصصة.",
    crmCardDescription: "تتبع رحلة العميل وأتمتة المتابعات مع نظام CRM متكامل.",
    analyticsCardDescription: "احصل على لوحة تحكم موحدة مع جميع مقاييس التسويق والرؤى الرئيسية.",

    // Ads Assistant
    adsTitle: "مساعد الإعلانات الذكي",
    adsDescription: "صف منتجك وجمهورك لتوليد أفكار إعلانية إبداعية.",
    productName: "اسم المنتج/الخدمة",
    productNamePlaceholder: "مثال: 'صنادل جلدية مصنوعة يدويًا'",
    targetAudience: "الجمهور المستهدف",
    targetAudiencePlaceholder: "مثال: 'رجال مهتمون بالموضة تتراوح أعمارهم بين 25-40 في دبي'",
    sellingPoints: "نقاط البيع الرئيسية (واحدة في كل سطر)",
    sellingPointsPlaceholder: "مثال:\nجلد إيطالي أصلي\nمريح ومتين\nشحن مجاني في دول مجلس التعاون الخليجي",
    generateAdIdeas: "توليد أفكار إعلانية",
    adIdeas: "أفكار إعلانية",
    adAngle: "زاوية الإعلان",
    headline: "العنوان الرئيسي",
    bodyCopy: "النص الأساسي",

    // Content Assistant
    contentTitle: "مصنع المحتوى القصير",
    contentDescription: "أنشئ أفكار مقاطع قصيرة جاهزة للنشر من نص أو صورة.",
    longContent: "المقالة/النص الكامل",
    longContentPlaceholder: "الصق مقالتك الكاملة أو نص الفيديو هنا...",
    generateShortClips: "توليد مقاطع قصيرة",
    shortClipIdeas: "أفكار مقاطع قصيرة",
    clipTitle: "عنوان المقطع",
    clipHook: "الخطاف (جملة البداية)",
    clipScript: "السيناريو",
    visualSuggestion: "اقتراح مرئي",
    fromText: "من نص",
    fromImage: "من صورة",
    uploadImage: "رفع صورة",
    imagePrompt: "موجه",
    imagePromptPlaceholder: "مثال: 'أنشئ سيناريو تيك توك مدته 15 ثانية حول هذا المنتج'",

    // SMM
    smmTitle: "خطة محتوى التواصل الاجتماعي",
    smmDescription: "أنشئ خطة محتوى لمدة أسبوع، معززة بالاتجاهات والأحداث ذات الصلة.",
    campaignTopic: "موضوع الحملة",
    campaignTopicPlaceholder: "مثال: 'عروض رمضان الخاصة'",
    platform: "المنصة",
    numberOfPosts: "عدد المنشورات",
    generatePlan: "توليد الخطة",
    smmResults: "خطة المحتوى التي تم إنشاؤها",
    day: "اليوم",
    contentType: "نوع المحتوى",
    caption: "التسمية التوضيحية",
    hashtags: "الهاشتاجات",
    
    // Landing Pages
    landingPagesTitle: "كاتب نصوص صفحات الهبوط الذكي",
    landingPagesDescription: "صف منتجك لتوليد نص مقنع لصفحة هبوط عالية التحويل.",
    productDescription: "وصف المنتج/الخدمة",
    productDescriptionPlaceholder: "مثال: دورة عبر الإنترنت لتعليم الخط العربي للمبتدئين.",
    generateCopy: "توليد النص",
    landingPageCopy: "نص صفحة الهبوط",
    subheadline: "العنوان الفرعي",

    // Email Marketing
    emailMarketingTitle: "مولد حملات البريد الإلكتروني الذكي",
    emailMarketingDescription: "حدد هدف حملتك لتوليد سلسلة من رسائل البريد الإلكتروني التسويقية الفعالة.",
    campaignGoal: "هدف الحملة",
    campaignGoalPlaceholder: "مثال: تخفيضات سريعة لمدة 3 أيام لمجموعتنا الجديدة.",
    generateEmails: "توليد رسائل البريد",
    emailCampaignIdeas: "أفكار حملة البريد الإلكتروني",
    subject: "الموضوع",
    
    // Affiliate Marketing
    affiliateMarketingTitle: "AI للتواصل مع الشركاء",
    affiliateMarketingDescription: "أنشئ بريدًا إلكترونيًا احترافيًا لتوظيف شركاء جدد لبرنامجك.",
    affiliateOffer: "عرض الشراكة",
    affiliateOfferPlaceholder: "مثال: عمولة 20% على جميع المبيعات، ملف تعريف ارتباط لمدة 30 يومًا.",
    generateOutreach: "توليد بريد التواصل",
    outreachEmail: "بريد التواصل",
    
    // CRM
    crmTitle: "منشئ شخصية العميل الذكي",
    crmDescription: "صف جمهورك المستهدف لإنشاء شخصية عميل مفصلة للتخطيط الاستراتيجي.",
    audienceDescriptionPlaceholder: "مثال: مهنيون شباب في دول مجلس التعاون الخليجي يتمتعون بالذكاء التقني ويهتمون بالمنتجات المستدامة.",
    generatePersona: "توليد شخصية العميل",
    customerPersona: "شخصية العميل",
    demographics: "البيانات الديموغرافية",
    goals: "الأهداف",
    painPoints: "نقاط الألم",
    
    // Analytics
    adAnalyticsTitle: "تحليلات الإعلانات",
    keyMetrics: "المقاييس الرئيسية",
    totalReach: "إجمالي الوصول",
    engagementRate: "معدل التفاعل",
    conversions: "التحويلات",
    adSpend: "الإنفاق الإعلاني",
    performanceOverTime: "الأداء عبر الزمن",
    channelPerformance: "أداء القنوات",
    topPerformingCampaigns: "الحملات الأفضل أداءً",
    campaign: "الحملة",
    status: "الحالة",
    spend: "الإنفاق",
    results: "النتائج",
    connectAccountsPrompt: "اربط حساباتك الإعلانية لرؤية بيانات أدائك.",
    connectAccountsDescription: "اذهب إلى الإعدادات لربط حساباتك على فيسبوك وانستجرام وفتح لوحة تحكم تحليلات الإعلانات الخاصة بك.",
    goToSettings: "اذهب إلى الإعدادات",

    // SEO
    seoTitle: "مساعد تحسين محركات البحث الذكي",
    seoDescription: "احصل على اقتراحات للكلمات المفتاحية وأنشئ ملخصات محتوى للوصول إلى مرتبة أعلى في محركات البحث.",
    searchDisclaimer: "يتم إنشاء النتائج بمساعدة بحث Google وقد لا تكون شاملة أو محدثة بالكامل.",
    topicPlaceholder: "مثال: 'أفضل مقاهي في الرياض'",
    generateKeywords: "توليد الكلمات المفتاحية",
    generateBrief: "توليد ملخص المحتوى",
    keywords: "الكلمات المفتاحية",
    searchIntent: "نية البحث",
    contentBrief: "ملخص المحتوى",
    title: "العنوان",
    hook: "الخطاف (جملة البداية)",
    introduction: "المقدمة",
    bodySections: "أقسام المحتوى",
    metaDescription: "وصف ميتا لتحسين محركات البحث",

    // Influencer
    influencersTitle: "اكتشاف المؤثرين بالذكاء الاصطناعي",
    influencersDescription: "ابحث عن المؤثرين المناسبين في مجالك وموقعك.",
    influencerDisclaimer: "توفر هذه الأداة اقتراحات بناءً على البيانات العامة وبحث Google. تحقق دائمًا من بيانات المؤثرين.",
    city: "المدينة",
    cityPlaceholder: "مثال: 'جدة'",
    category: "الفئة / المجال",
    categoryPlaceholder: "مثال: 'مدون طعام'",
    followerRange: "نطاق المتابعين",
    findInfluencers: "ابحث عن مؤثرين",
    influencerResults: "اقتراحات المؤثرين",
    followers: "المتابعون",
    bio: "السيرة الذاتية",
    viewProfile: "عرض الملف الشخصي",

    // Optimizer
    optimizerTitle: "محسن وسائل التواصل الاجتماعي",
    optimizerDescription: "احصل على توصيات بأفضل أوقات النشر وأفكار للمحتوى بناءً على مجالك.",
    industry: "الصناعة / المجال",
    industryPlaceholder: "مثال: 'تجارة إلكترونية للأزياء'",
    getRecommendations: "احصل على توصيات",
    optimizerResults: "اقتراحات التحسين",
    postingTimes: "أفضل أوقات النشر",
    contentIdeas: "أفكار للمحتوى",

    // Testing Suite
    testingTitle: "مجموعة اختبار API",
    testingDescription: "قم بإجراء سلسلة من الاختبارات التلقائية على Gemini API للتأكد من أن جميع نقاط النهاية تعمل بشكل صحيح.",
    runTests: "تشغيل جميع الاختبارات",
    running: "قيد التشغيل...",
    testResults: "نتائج الاختبار",
    passed: "نجح",
    failed: "فشل",
    
    // Settings
    settingsTitle: "الإعدادات",
    connections: "الربط",
    connectionsDescription: "اربط حساباتك على وسائل التواصل الاجتماعي والإعلانات لفتح ميزات التحليلات والأتمتة القوية.",
    connect: "ربط",
    disconnect: "فصل",
    connected: "متصل",
    
    // OAuth Flow
    connectToPlatform: "الربط مع {platform}",
    permissionsRequest: "سيسمح هذا لمسوّق الذكاء الاصطناعي بما يلي:",
    readAdPerformance: "قراءة بيانات أداء الإعلانات",
    allow: "سماح",
    cancel: "إلغاء",
    finalizingConnection: "جاري إنهاء الاتصال...",
    connectionSuccessful: "تم الاتصال بنجاح!",
    redirectingMessage: "جاري إعادتك إلى الإعدادات...",
    connectionFailed: "فشل الاتصال",
    connectionErrorMessage: "حدث خطأ ما. يرجى المحاولة مرة أخرى.",
    backToSettings: "العودة إلى الإعدادات",
    redirectingToPlatform: "جاري توجيهك إلى {platform}...",
  },
};
